### ISSUE TITLE
Pass function arguments to the lambda

### ISSUE THREAD

**Issue by eshansingh** [deadpixi/contracts#1]
Currently, all contract functions magically get the arguments as well the variable `__result__`. Not only is this strange, it also causes most linters to error out. Is it possible to change this behaviour so that the function arguments are passed in as arguments to the lambda instead? Similar for class invariants - `__instance__` should be passed in.

**Comment by deadpixi** [comment]
Hello @eshansingh 

Please check the latest code here on GitHub. I believe it solves your problems. The documentation and tests have been updated.

Please close this issue if this works for you. Thanks!

**Comment by eshansingh** [comment]
Thanks a whole lot for being so quick!
